
export interface IOrder {
    isOrderAsk: boolean,
    signer: string,
    collectionAddress: string,
    price: string,
    tokenId: string,
    chain: string,
    amount: number,
    strategy: string,
    currencyAddress: string,
    nonce: string,
    startTime: number,
    endTime: number,
    minPercentageToAsk: number,
    signature: string,
    params: string,
    status: string,
    v: number,
    r: string,
    s: string,
}
  
export interface ICollection {
    owner: string,
    symbol: string,
    type: string,
    websiteLink: string,
    facebookLink: string,
    twitterLink: string,
    instagramLink: string,
    telegramLink: string,
    mediumLink: string,
    discordLink: string,
    isVerified: boolean,
    isExplicit: boolean,
    standard: {
        type: string,
        default: 'erc'
    },

    name: string,
    network: string,
    discord: string,
    website: string,
    twitter: string,
    medium: string,
    instagram: string,
    telegram: string,
    banner_image: string,
    profile_image: string,
    description: string,
    col_url: string,
    col_name: string,
    count: number,
    by_name: boolean,
    address: string,
    artblocks: boolean,
    attrs: object,
    chain: string,
}

export interface ICreateOrderRequest {
    signature: string,
    collection: string,
    tokenId: string,
    chain: string,
    signer: string,
    strategy: string,
    isOrderAsk: boolean,
    currency: string,
    nonce: string,
    amount: number,
    price: string,
    startTime: number,
    endTime: number,
    minPercentageToAsk: number,
    params: string,
}

export interface IGetOrderRequest {
    isOrderAsk: boolean,
    chain: string,
    collection: string,
    tokenId: string,
    signer: string,
    nonce: string,
    strategy: string,
    currency: string,
    price: any,
    startTime: string,
    endTime: string,
    status: [string],
    pagination: any,
    sort: string
}